addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/science/vips --with-webp --with-graphicsmagick; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" -a "$CC" == "gcc" ]; then export CC=gcc-4.8; export CXX=g++-4.8; fi
language: node_js
matrix:
    include:
       - os: linux
         env: CXX=g++-4.8
         after_script:
           - npm run coverage
           - npm run coveralls
           - npm run codeclimate
node_js:
  - "node"
os:
  - osx