addons:
  apt:
    packages:
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/science/vips --with-webp --with-graphicsmagick; fi
env:
  - CXX=g++-4.8
language: node_js
node_js:
  - "node"
os:
  - linux
  - osx